### PR TITLE
forge: update to forge-std rather than ds-test + Cheats.sol

### LINKED ISSUE #9: forge: update to forge-std rather than ds-test + Cheats.sol

### PR DESCRIPTION
**Pull request by davisshaver**
Closes https://github.com/holic/web3-scaffold/issues/9

### CODE REVIEW

**Comment by frolic** [comment]
🙏

**Comment by frolic** [comment]
I'm having trouble pulling this down locally to run tests (since CI didn't seem to be hooked up properly). I always seem to be fighting the git submodules approach to forge dependencies. Any advice for getting this working?

Alternatively, can you push up a new change to include this recent commit: https://github.com/holic/web3-scaffold/commit/fecf8c375bb85238ff8af5558f5f3de8a9133779

Hoping this will cause the CI tests to run for PRs to main.

**Comment by davisshaver** [comment]
Hey @holic! Thanks for reviewing. I merged `main` but it looks like I need maintainer approval to run workflows as a first-time contributor.

For installing packages with Forge, I ran `forge install` to bring the submodules in, then `forge remove ds-test` to remove `ds-test`, and then `forge install foundry-rs/forge-std` to add the Forge Standard Library.

The only potential issue I see with the current CI setup is that we will want to pull in submodules recursively on checkout, since for example the Forge Standard Library uses `ds-test` under the hood. I'm going to push one more commit now to address this.

**Comment by frolic** [comment]
🙈  Sorry for the commit spam, OSX vs Unix filename case sensitivity caught me

**Pull request merged**
